---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE_LINTERS:
  - SPELL_CSPELL
  - SPELL_LYCHEE

DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS

GO_GOLANGCI_LINT_PRE_COMMANDS: [{ "command": "cd ./app", "continue_if_failed": false, "cwd": "workspace"}]
EMAIL_REPORTER: false
FILEIO_REPORTER: false
MARKDOWN_SUMMARY_REPORTER: true
SHOW_ELAPSED_TIME: true